version: 0.1

sphinx:
    configuration: docs/conf.py
    fail_on_warning: true

build:
    image: latest

python:
    version: 3.8
    install:
        - method: pip
          path: .

conda:
    environment: docs/environment.yml